version: '3'
services:
        php:
                image: php:7.2-apache
                volumes:
                        - ./src/:/var/www/html
                        - ./apache2_conf/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
                ports:
                        - 80:80
                deploy:
                        resources:
                                limits:
                                        cpus: '0.50'
                                        memory: 50M





