version: '3'
services:
        php:
                build: ./dockerfile
                volumes:
                        - ./src/:/var/www/html
                        - ./containers_volumes/apache2_conf/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
                        - ./containers_volumes/php_conf/php.ini-development:/usr/local/etc/php/php.ini-development
                ports:
                        - 80:80
                deploy:
                        resources:
                                limits:
                                        cpus: '0.50'
                                        memory: 50M
                networks:
                        - docker-network

        db:
                image: postgres
                volumes:
                        - ./postgres_data:/var/lib/postgresql/data
                ports:
                        - 5432:5432
                environment:
                        POSTGRES_PASSWORD: postgres-admin
                deploy:
                        resources:
                                limits:
                                        cpus: '0.50'
                                        memory: 50M
                networks:
                        - docker-network


networks: 
        docker-network:
                driver: bridge
